extends Node

# ComboPointSystem.gd - Manages combo points for Rogues
# Combo points are generated by certain abilities and consumed by finishers

func _get_logger():
	return get_node_or_null("/root/Logger")

func _log_info(source: String, message: String):
	var logger = _get_logger()
	if logger:
		logger.info(source, message)
	else:
		print("[%s] [INFO] %s" % [source, message])

func _log_debug(source: String, message: String):
	var logger = _get_logger()
	if logger:
		logger.debug(source, message)
	else:
		print("[%s] [DEBUG] %s" % [source, message])

# Map<hero_id, combo_points>
var combo_points: Dictionary = {}
const MAX_COMBO_POINTS: int = 5

func _ready():
	_log_info("ComboPointSystem", "Initialized")

# Get current combo points for a hero
func get_combo_points(hero_id: String) -> int:
	return combo_points.get(hero_id, 0)

# Add combo points to a hero
func add_combo_points(hero_id: String, amount: int):
	var current = get_combo_points(hero_id)
	var new_total = min(current + amount, MAX_COMBO_POINTS)
	combo_points[hero_id] = new_total
	_log_debug("ComboPointSystem", "%s gained %d combo points (total: %d)" % [hero_id, amount, new_total])

# Consume combo points (used by finishers)
func consume_combo_points(hero_id: String, amount: int = MAX_COMBO_POINTS) -> int:
	var current = get_combo_points(hero_id)
	var consumed = min(current, amount)
	combo_points[hero_id] = max(0, current - consumed)
	_log_debug("ComboPointSystem", "%s consumed %d combo points (remaining: %d)" % [hero_id, consumed, combo_points[hero_id]])
	return consumed

# Reset combo points for a hero (e.g., when target dies or combat ends)
func reset_combo_points(hero_id: String):
	combo_points[hero_id] = 0
	_log_debug("ComboPointSystem", "%s combo points reset" % hero_id)

# Check if hero has enough combo points for a finisher
func has_combo_points(hero_id: String, required: int = 1) -> bool:
	return get_combo_points(hero_id) >= required

# Clear all combo points (e.g., when combat ends)
func clear_all_combo_points():
	combo_points.clear()
